# comenterio
GET http://localhost:3000/users

### comenterio
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Amanda",
    "email": "amanda4@email.com",
    "password": "1234"
}

### comenterio


### comenterio
