# comenterio
GET http://localhost:3000/users

### common user
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Amanda",
    "email": "amanda@email.com",
    "password": "1234"
}

### partner user
POST http://localhost:3000/partners/users
Content-Type: application/json

{
    "name": "Amanda",
    "email": "amanda1@email.com",
    "password": "1234"
}


### comenterio
